

ACS_YEAR = 2022
GEOID_COLUMN = "GEOID"
BUFFER_SIZE = -5

CENSUS_MODESHARE_VARIABLES = {
    "MODESHARE_TOTAL": "B08301_001E",
    "TRANSIT": "B08301_010E",
    "BIKE": "B08301_018E",
    "WALK": "B08301_019E",
    "WFH": "B08301_021E",
}

CENSUS_CARLESSNESS_VARIABLES = {
    "TOTAL": "B25044_001E",
    "NO_VEHICLE_RENTER": "B25044_010E",
    "NO_VEHICLE_OWNER": "B25044_003E",
}

CENSUS_TOTAL_POPULATION_VARIABLES = {
    "TOTAL": "B01003_001E"
}

SMART_LOCATION_CRS = 102039
TIGER_CRS = 4269
BLOCK_GROUP_BUFFER_SIZE = 1000

EJSCREEN_COLUMN = "P_PTRAF"
SMART_LOCATION_JOB_ACCESSIBILITY_COLUMN = "D5BR"
SMART_LOCATION_NATIONAL_WALKABILITY_INDEX_COLUMN = "NatWalkInd"
SMART_LOCATION_JOB_DENSITY_COLUMN = "D1C"
SMART_LOCATION_POPULATION_DENSITY_COLUMN = "D1B"
SMART_LOCATION_RETAIL_JOB_DENSITY = "D1C8_RET"
SMART_LOCATION_ENTERTAINMENT_JOB_DENSITY = "D1C8_ENT"
SMART_LOCATION_RAW_JOBS = "TotEmp"
SMART_LOCATION_COLUMNS = [
    SMART_LOCATION_JOB_ACCESSIBILITY_COLUMN,
    SMART_LOCATION_NATIONAL_WALKABILITY_INDEX_COLUMN,
    SMART_LOCATION_JOB_DENSITY_COLUMN,
    SMART_LOCATION_POPULATION_DENSITY_COLUMN,
    SMART_LOCATION_RETAIL_JOB_DENSITY,
    SMART_LOCATION_ENTERTAINMENT_JOB_DENSITY,
    SMART_LOCATION_RAW_JOBS,
]

EJSCREEN_NAME = "National Traffic Proximity & Volume Percentile"
SMART_LOCATION_JOB_ACCESSIBILITY_NAME = "Job Accessibility by Transit in 45 mins, weighted"
SMART_LOCATION_NATIONAL_WALKABILITY_INDEX_NAME = "National Walkability Index"
SMART_LOCATION_JOB_DENSITY_NAME = "Job Density (jobs/acre)"
SMART_LOCATION_POPULATION_DENSITY_NAME = "Population Density (people/acre)"
SMART_LOCATION_RETAIL_JOB_DENSITY_NAME = "Retail Job Density (jobs/acre)"
SMART_LOCATION_ENTERTAINMENT_JOB_DENSITY_NAME = "Entertainment Job Density (jobs/acre)"
SMART_LOCATION_RETAIL_ENTERTAINMENT_JOB_DENSITY_NAME = "Retail and Entertainment Job Density (jobs/acre)"
SMART_LOCATION_RAW_JOBS_NAME = "Total # Jobs"
CENSUS_CARLESSNESS_NAME = "Carlessness Rate"
CENSUS_MODESHARE_NAME = "Sustainable Mobility TTW Modeshare"
CENSUS_POPULATION_NAME = "Total Population"
GEOID_NAME = "Block Group GeoID"
