from SEDataObjects.BaseLayer.constants import SMART_LOCATION_JOB_ACCESSIBILITY_COLUMN, SMART_LOCATION_JOB_ACCESSIBILITY_NAME
from SEDataObjects.BaseLayer.entities import BaseLayerSmartLocation


class SmartLocationJobAccessibility(BaseLayerSmartLocation):
    metric_field_id = SMART_LOCATION_JOB_ACCESSIBILITY_COLUMN
    metric_alias = SMART_LOCATION_JOB_ACCESSIBILITY_NAME